### ISSUE TITLE
Error SPE fitting with multiprocessing

### ISSUE THREAD

**Issue by tibaldo** [cta-observatory/nectarchain#89]
I was going through the tutorial on SPE fitting by @guillaumegrolleron [https://github.com/cta-observatory/nectarchain/blob/master/notebooks/tool_implementation/tuto_SPE.py](url), and I got the error below at the 'finish' step. I was using 'multiproc=True' and 'nproc=4' (number of CPUS on my machine). Note that everything works fine (no errors, reasonable PE spectra and gain values) if I set 'multiproc=False'at the step of component creation.
Could someone please help me to figure out what the problem is?

```
"""
Traceback (most recent call last):
  File "/Users/ltibaldo/anaconda3/envs/nectarchain-ctapipe0.19/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/ltibaldo/anaconda3/envs/nectarchain-ctapipe0.19/lib/python3.10/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/Users/ltibaldo/Software/GitHub/nectarchain/src/nectarchain/makers/component/spe/spe_algorithm.py", line 679, in run_fit
    __class__.__fit_array[i].migrad()
TypeError: 'NoneType' object is not subscriptable
"""

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
File ~/Software/GitHub/nectarchain/src/nectarchain/makers/component/spe/spe_algorithm.py:735, in SPEnominalalgorithm.run(self, pixels_id, display, **kwargs)
    734 try:
--> 735     res = result.get()
    736 except Exception as e:

File ~/anaconda3/envs/nectarchain-ctapipe0.19/lib/python3.10/multiprocessing/pool.py:774, in ApplyResult.get(self, timeout)
    773 else:
--> 774     raise self._value

TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
Input In [7], in <cell line: 1>()
----> 1 output = tool.finish(return_output_component=True, display=True, figpath=os.getcwd())

File ~/Software/GitHub/nectarchain/src/nectarchain/makers/core.py:390, in EventsLoopNectarCAMCalibrationTool.finish(self, return_output_component, *args, **kwargs)
    387 def finish(self, return_output_component=False, *args, **kwargs):
    388     self.log.info("finishing Tool")
--> 390     output = self._finish_components(*args, **kwargs)
    392     self.writer.close()
    393     super().finish()

File ~/Software/GitHub/nectarchain/src/nectarchain/makers/core.py:402, in EventsLoopNectarCAMCalibrationTool._finish_components(self, *args, **kwargs)
    400 output = []
    401 for component in self.components:
--> 402     output.append(component.finish(*args, **kwargs))
    403 log.info(output)
    404 for i, _output in enumerate(output):

File ~/Software/GitHub/nectarchain/src/nectarchain/makers/component/FlatFieldSPEComponent.py:136, in FlatFieldSingleNominalSPENectarCAMComponent.finish(self, *args, **kwargs)
    132 if not (is_empty):
    133     spe_fit = eval(self.SPEfitalgorithm).create_from_chargesContainer(
    134         self._chargesContainers, parent=self, **self._SPEfitalgorithm_kwargs
    135     )
--> 136     fit_output = spe_fit.run(pixels_id=self.asked_pixels_id, *args, **kwargs)
    137     n_asked_pix = (
    138         len(self._chargesContainers.pixels_id)
    139         if self.asked_pixels_id is None
    140         else len(self.asked_pixels_id)
    141     )
    142     conv_rate = np.sum(spe_fit.results.is_valid) / n_asked_pix

File ~/Software/GitHub/nectarchain/src/nectarchain/makers/component/spe/spe_algorithm.py:737, in SPEnominalalgorithm.run(self, pixels_id, display, **kwargs)
    735     res = result.get()
    736 except Exception as e:
--> 737     self.log.error(e, exc_info=True)
    738     raise e
    739 self.log.debug(str(res))

File ~/anaconda3/envs/nectarchain-ctapipe0.19/lib/python3.10/logging/__init__.py:1506, in Logger.error(self, msg, *args, **kwargs)
   1497 """
   1498 Log 'msg % args' with severity 'ERROR'.
   1499 
   (...)
   1503 logger.error("Houston, we have a %s", "major problem", exc_info=1)
   1504 """
   1505 if self.isEnabledFor(ERROR):
-> 1506     self._log(ERROR, msg, args, **kwargs)

File ~/anaconda3/envs/nectarchain-ctapipe0.19/lib/python3.10/logging/__init__.py:1624, in Logger._log(self, level, msg, args, exc_info, extra, stack_info, stacklevel)
   1621         exc_info = sys.exc_info()
   1622 record = self.makeRecord(self.name, level, fn, lno, msg, args,
   1623                          exc_info, func, extra, sinfo)
-> 1624 self.handle(record)

File ~/anaconda3/envs/nectarchain-ctapipe0.19/lib/python3.10/logging/__init__.py:1634, in Logger.handle(self, record)
   1627 """
   1628 Call the handlers for the specified record.
   1629 
   1630 This method is used for unpickled records received from a socket, as
   1631 well as those created locally. Logger-level filtering is applied.
   1632 """
   1633 if (not self.disabled) and self.filter(record):
-> 1634     self.callHandlers(record)

File ~/anaconda3/envs/nectarchain-ctapipe0.19/lib/python3.10/logging/__init__.py:1696, in Logger.callHandlers(self, record)
   1694     found = found + 1
   1695     if record.levelno >= hdlr.level:
-> 1696         hdlr.handle(record)
   1697 if not c.propagate:
   1698     c = None    #break out

File ~/anaconda3/envs/nectarchain-ctapipe0.19/lib/python3.10/site-packages/ctapipe/core/tool.py:46, in CollectTraitWarningsHandler.handle(self, record)
     45 def handle(self, record):
---> 46     if self.regex.match(record.msg) and record.levelno == logging.WARNING:
     47         self.errors.append(record.msg)

TypeError: expected string or bytes-like object
```

**Comment by jlenain** [comment]
Hi @tibaldo !

Since the SPE fit seems to run fine without multiprocessing, I am starting to wonder whether you would not hit a multiprocessing issue with your Mac (as opposed to a PC).

Could you please maybe try again, activating the multiprocessing option in the SPE fit, but using only 1 CPU ?

Another test, could you please also try this standalone minimal working example using `mutliprocessing` ?
```
from multiprocessing import Pool, cpu_count
import time

def test_function(i):
    print("function starts" + str(i))
    time.sleep(1)
    print("function ends" + str(i))

if __name__ == '__main__':
    with Pool(cpu_count()) as pool:
        result = pool.starmap_async(
            test_function,
            [(i,) for i in range(20)])
        result.wait()
    res = result.get()
```

**Comment by tibaldo** [comment]
Thank you for the feedback @jlenain.

I've used the multiprocessing package extensively on Macs and in general I can say that it works just fine. Nevertheless I tried the simple test script you provided. It run just fine as expected printing
```
function starts0
function starts2
function starts4
function starts6
function ends0
...
```
I also tried to rerun the tutorial with 'multiproc=True' and 'nproc=1'. I got exactly the same error as with 'nproc=4'.

**Comment by jlenain** [comment]
Thanks, @tibaldo . Then, I can discard this hypothesis (Mac vs PC).

For the moment, I am clueless...
I re-tested the tutorial from my laptop, both enabling/disabling the multiprocessing, and everything runs fine on my side...

**Comment by guillaumegrolleron** [comment]
Hi @tibaldo, @jlenain, 
Same for me I have no clear idea yet...
Just to have a check, what is your `numpy` and `minuit` version ?

**Comment by jlenain** [comment]
Maybe some meat for thoughts: https://github.com/python/cpython/issues/83595#issuecomment-1631951106

**Comment by tibaldo** [comment]
Thank you @jlenain The post describes an error when the results from the pool are returned. Here the problem seems to happen inside the function run_fit
```
File "/Users/ltibaldo/Software/GitHub/nectarchain/src/nectarchain/makers/component/spe/spe_algorithm.py", line 679, in run_fit
    __class__.__fit_array[i].migrad()
TypeError: 'NoneType' object is not subscriptable
```
as if '__class__.__fit_array' was not properly passed to the function. I though about it but I cannot see what may go wrong.

@guillaumegrolleron : in my environment I have Python 3.10.11, numpy 1.24.3 and iminuit 2.21.3

**Comment by guillaumegrolleron** [comment]
1. Fine, at least we can exclude this explanation
2. Do you ask only for pixels id 52 ? 

Could you please run again the script with `log_level = 10`, a message should be written after the creation of fit instance

**Comment by tibaldo** [comment]
Here's the new log file. It seems less complete than the output on screen, so I'am also pasting that below.
[SPEfit_3936.log](https://github.com/cta-observatory/nectarchain/files/14056209/SPEfit_3936.log)

```
2024-01-25 18:50:17,478 INFO [nectarchain.FlatFieldSPENominalStdNectarCAM] (core.finish): finishing Tool
2024-01-25 18:50:17,482 INFO [nectarchain.FlatFieldSPENominalStdNectarCAM] (core._finish_components): finishing components and writting to output file
2024-01-25 18:50:24,745 DEBUG [nectarchain.makers.component.chargesComponent] (chargesComponent._histo): there are 0 broken pixels (charge stays at same level for each events)
2024-01-25 18:50:27,316 DEBUG [nectarchain.makers.component.chargesComponent] (chargesComponent._histo): histogram hg computation time : 1.6356432437896729 sec
2024-01-25 18:50:28,980 INFO [nectarchain.FlatFieldSPENominalStdNectarCAM.FlatFieldSingleNominalSPEStdNectarCAMComponent.SPEnominalStdalgorithm] (spe_algorithm.__fix_parameters): updating parameters by fixing pp and n
2024-01-25 18:50:28,981 INFO [nectarchain.FlatFieldSPENominalStdNectarCAM.FlatFieldSingleNominalSPEStdNectarCAMComponent.SPEnominalStdalgorithm] (spe_algorithm.run): running maker
2024-01-25 18:50:28,982 INFO [nectarchain.FlatFieldSPENominalStdNectarCAM.FlatFieldSingleNominalSPEStdNectarCAMComponent.SPEnominalStdalgorithm] (spe_algorithm.run): checking asked pixels id
2024-01-25 18:50:28,982 DEBUG [nectarchain.FlatFieldSPENominalStdNectarCAM.FlatFieldSingleNominalSPEStdNectarCAMComponent.SPEnominalStdalgorithm] (spe_algorithm.run): checking that asked pixels id are in data
2024-01-25 18:50:28,983 INFO [nectarchain.FlatFieldSPENominalStdNectarCAM.FlatFieldSingleNominalSPEStdNectarCAMComponent.SPEnominalStdalgorithm] (spe_algorithm.run): creation of the fits instance array
2024-01-25 18:50:29,012 DEBUG [nectarchain.makers.component.spe.spe_algorithm] (spe_algorithm._get_mean_gaussian_fit): plotting figures with prefit parameters computation
2024-01-25 18:50:30,500 DEBUG [nectarchain.makers.component.spe.spe_algorithm] (spe_algorithm._get_mean_gaussian_fit): plotting figures with prefit parameters computation
2024-01-25 18:50:30,765 DEBUG [nectarchain.makers.component.spe.spe_algorithm] (spe_algorithm._update_parameters): pedestal updated: name : pedestal, value : 2994.0113203312476, error : nan, unit : , min : 2982.1582255943613, max : 3005.864415068134,frozen : False
2024-01-25 18:50:30,766 DEBUG [nectarchain.makers.component.spe.spe_algorithm] (spe_algorithm._update_parameters): pedestalWidth updated: 11.853094736886305
2024-01-25 18:50:30,766 DEBUG [nectarchain.makers.component.spe.spe_algorithm] (spe_algorithm._update_parameters): mean updated: name : mean, value : 69.27334646428744, error : nan, unit : , min : 23.544783201868995, max : 115.00190972670589,frozen : False
2024-01-25 18:50:30,767 INFO [nectarchain.FlatFieldSPENominalStdNectarCAM.FlatFieldSingleNominalSPEStdNectarCAMComponent.SPEnominalStdalgorithm] (spe_algorithm._make_fit_array_from_parameters): creation of fit instance for pixel: 52
2024-01-25 18:50:30,770 DEBUG [nectarchain.FlatFieldSPENominalStdNectarCAM.FlatFieldSingleNominalSPEStdNectarCAMComponent.SPEnominalStdalgorithm] (spe_algorithm._make_fit_array_from_parameters): fit created
2024-01-25 18:50:30,771 INFO [nectarchain.FlatFieldSPENominalStdNectarCAM.FlatFieldSingleNominalSPEStdNectarCAMComponent.SPEnominalStdalgorithm] (spe_algorithm.run): running fits
2024-01-25 18:50:30,773 INFO [nectarchain.FlatFieldSPENominalStdNectarCAM.FlatFieldSingleNominalSPEStdNectarCAMComponent.SPEnominalStdalgorithm] (spe_algorithm.run): pooling with nproc 1, chunksize 1
```

**Comment by guillaumegrolleron** [comment]
Your issue is unfortunately very strange... 
As it works without multiprocessing, it means that the class attribute `__class__.__fit_array` is well initialized and is not None. 
However, it seems that inside the multiprocessing `Pool.starmap_async`, inside the call to run_fit, the attribut is still equal to None. I'm suspecting that the execution scope are not the same. But I can't reproduce your behaviour and it's the first time I face it. 
Could you please give my your environment file (you can get it with `conda env export > env.yml`) . I will try to reproduce this bug.

**Comment by tibaldo** [comment]
Thank you @guillaumegrolleron. I'll send the environment file via email because GitHub does not allow attachments in yml

**Comment by tibaldo** [comment]
I made some tests and the issue is that __class__.__fit_array is None inside run_fit when using multprocessing. The issue seems similar to the one described here [https://stackoverflow.com/questions/70114013/class-variable-become-empty-in-multiprocessing-pool-map](url). Not sure how to apply the suggestions there to solve it though, suggestions would be appreciated.

**Comment by guillaumegrolleron** [comment]
With @vmarandon we investigated your problem and it seems to be specific to macOS. Indeed I guess that the `multiprocessing` library doesn't manage the execution scope in the same way on linux than on mac. The __fit_array attribute isn't well shared between process on mac. 
When I developed the SPE fit code I was quite surprised that my implementation was correct, and it was also the most efficient. The problem is that it is apparently platform specific...

I have no clear suggestion, we could try to use dictionary or specific data structure implemented in the `multiprocessing` library which manage memory sharing. However I have ever tried this structures and it appeared that it was not much efficient compared to the implementation which is done here. 

An other solution is indeed in the link you shared, I didn't know it is possible to initialize global variable through the multiprocessing `Pool` constructor, this solution could be very nice and easy, we have to check. I have unfortunately no much time to work on `nectarchain`, but I will try to have a look in the upcoming week.

**Comment by tibaldo** [comment]
More information is available here
[https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods](url)
I guess the code was developed and tested only on Linux so far? The start method for MacOS and Windows is 'spawn', as opposed to 'fork' on Linux. From the description of 'spawn' I guess it's expected that '__class__.__fit_array' defaults to 'None' when multiprocessing is used.
It's not a big issue for me personally. I can use a Linux machine (with more CPUs than my laptop) if/when I want to go parallel computing.
It may become a problem in the future. According to the webpage the default start method will change away from fork for Linux too in Python 3.14. Then multiprocessing may not work anymore in the current implementation.

**Comment by jlenain** [comment]
Thanks a lot for digging into this, @tibaldo !
I think the different ways (spawn vs fork) multiprocessing threads are initiated from the parent thread between Linux and macOS - not talking about Windows here, which is not supported by `nectarchain` anyway - are indeed the cause.

@guillaumegrolleron , do you think you can try - later, when you have a bit of time - to indeed explicitly pass objects which needs to be changed by `run_fit` within the initialization of `Pool` ?

**Comment by guillaumegrolleron** [comment]
@jlenain sure I will try, I think the easiest way should be to perform a copy of the `__fit__array` attribute and to put it in a global variable when the `Pool` is created.
