### ISSUE TITLE
Wrong input path in DQM when automagically fetching runs from DIRAC

### ISSUE THREAD

**Issue by jlenain** [cta-observatory/nectarchain#96]
**Describe the bug**
The DQM searches for input files in the wrong path when run files are automatically downloaded from DIRAC.

**To Reproduce**
Steps to reproduce the behavior, under `nectarchain` version `0.1.7`:
1. Initialize a DIRAC proxy
2. Set NECTARCAMDATA to some path
3. Try to run the DQM:
```shell
python src/nectarchain/dqm/start_dqm.py $NECTARCAMDATA $NECTARCAMDATA -r 4333 -p -n 
```

**Expected behavior**
The DQM fetch run files from DIRAC and stores them in the correct input path.

**Supporting information**
```shell
python src/nectarchain/dqm/start_dqm.py $NECTARCAMDATA $NECTARCAMDATA -r 4333 -p -n 
Input file path: /tmp/jlenain/scratch
Output path: /tmp/jlenain/scratch
Input files:
/tmp/jlenain/scratch/NectarCAM.Run4333.0000.fits.fz
NectarCAM.Run4333.0001.fits.fz
NectarCAM.Run4333.0002.fits.fz
NectarCAM.Run4333.0003.fits.fz
NectarCAM.Run4333.0004.fits.fz
NectarCAM.Run4333.0005.fits.fz
Plot: True
Noped: True
/tmp/jlenain/scratch/NectarCAM.Run4333.0000.fits.fz
Traceback (most recent call last):
  File "/home/jlenain/local/src/python/cta-observatory/nectarchain/src/nectarchain/dqm/start_dqm.py", line 109, in <module>
    reader = EventSource(input_url=path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jlenain/local/opt/mambaforge/envs/nectar-dev/lib/python3.11/site-packages/ctapipe/io/eventsource.py", line 130, in __new__
    subcls = cls._find_compatible_source(input_url)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jlenain/local/opt/mambaforge/envs/nectar-dev/lib/python3.11/site-packages/ctapipe/io/eventsource.py", line 354, in _find_compatible_source
    raise TraitError(
traitlets.traitlets.TraitError: input_url /tmp/jlenain/scratch/NectarCAM.Run4333.0000.fits.fz is not an existing file  and no EventSource implementation claimed compatibility
```

**Additional context**
The `DataManagement` class downloads files from DIRAC under `$NECTARCAMDATA/runs`, and the DQM searches for them from `$NECTARCAMDATA`.
Simple solution, in `start_dqm.py`, change:
```python
path = f"{NectarPath}/{path1}"
```
by:
```python
path = f"{NectarPath}/runs/{path1}"
```

**Comment by mdpunch** [comment]
Thanks, will modify this too...

**Comment by jlenain** [comment]
Re-open this. Following #95 , it appears that:

```python
for arg in args.input_files[1:]:
    path2 = f"{NectarPath}/{arg}"
    print(path2)
```
should also be modified by:
```python
for arg in args.input_files[1:]:
    path2 = f"{NectarPath}/runs/{arg}"
    print(path2)
```
